name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "requirements.txt"
          allow_failure: true
      - name: Cache dependency
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          architecture: x64
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check Python version
        run: python --version
      - name: Check Pip version
        run: pip --version
      - name: Check formatting
        run: black --check .
